# Generated by Django 5.0.4 on 2024-05-15 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_address_useraddress_verificationotp'),
        ('common', '0002_alter_country_options_alter_customerfeedback_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='common.region'),
            preserve_default=False,
        ),
    ]
