# Generated by Django 5.0.4 on 2024-05-17 12:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('name', models.CharField(max_length=50, verbose_name='Country name')),
                ('code', models.CharField(max_length=10, verbose_name='Country code')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
            bases=('common.basemodel',),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('file', models.FileField(upload_to='files/', verbose_name='File')),
                ('type', models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('music', 'Music'), ('video', 'Video')], max_length=10, verbose_name='File type')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Medias',
            },
            bases=('common.basemodel',),
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('description', models.TextField(verbose_name='Description')),
                ('rank', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rank')),
                ('customer_name', models.CharField(max_length=60, verbose_name='Customer name')),
                ('customer_position', models.CharField(max_length=60, verbose_name='Customer position')),
                ('customer_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_images', to='common.media')),
            ],
            options={
                'verbose_name': 'Customer feedback',
                'verbose_name_plural': 'Customer feedbacks',
            },
            bases=('common.basemodel',),
        ),
        migrations.CreateModel(
            name='OurInstagramStory',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('story_link', models.URLField(verbose_name='Story link')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_stories', to='common.media')),
            ],
            options={
                'verbose_name': 'Instagram story',
                'verbose_name_plural': 'Instagram stories',
            },
            bases=('common.basemodel',),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('name', models.CharField(max_length=50, verbose_name='Region name')),
                ('zip_code', models.CharField(max_length=20, verbose_name='Zip code')),
                ('country_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='common.country')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
            bases=('common.basemodel',),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('home_title', models.CharField(max_length=120, verbose_name='Title')),
                ('home_subtitle', models.CharField(max_length=120, verbose_name='Subtitle')),
                ('home_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.media')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
            bases=('common.basemodel',),
        ),
    ]
