# Generated by Django 5.0.4 on 2024-05-27 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourinstagramstory',
            name='story_link',
            field=models.URLField(validators=[django.core.validators.URLValidator()], verbose_name='Story link'),
        ),
        migrations.AlterField(
            model_name='region',
            name='zip_code',
            field=models.CharField(max_length=20, null=True, verbose_name='Zip code'),
        ),
    ]
